name: 构建全部
on:
  workflow_dispatch:
    inputs:
      OnePlus13:
        description: "OnePlus13"
        type: boolean
        default: false
      OnePlus13T:
        description: "OnePlus13T"
        type: boolean
        default: false
      OnePlusAce5Pro:
        description: "OnePlus Ace 5 Pro"
        type: boolean
        default: false
      OnePlus13_KPM:
        description: "OnePlus13_KPM"
        type: boolean
        default: false
      OnePlus13T_KPM:
        description: "OnePlus13T_KPM"
        type: boolean
        default: false
      OnePlusAce5Pro_KPM:
        description: "OnePlus Ace 5 Pro_KPM"
        type: boolean
        default: false
      

jobs:
  OnePlus13:
    if: ${{ github.event.inputs.OnePlus13 == 'true' }}
    uses: ./.github/workflows/OnePlus13.yml
    secrets: inherit
    
  OnePlus13T:
    if: ${{ github.event.inputs.OnePlus13T == 'true' }}
    uses: ./.github/workflows/OnePlus13T.yml
    secrets: inherit
    
  OnePlusAce5Pro:
    if: ${{ github.event.inputs.OnePlusAce5Pro == 'true' }}
    uses: ./.github/workflows/OnePlusAce5Pro.yml
    secrets: inherit

  OnePlus13_KPM:
    if: ${{ github.event.inputs.OnePlus13_KPM == 'true' }}
    uses: ./.github/workflows/OnePlus13_KPM.yml
    secrets: inherit
    
  OnePlus13T_KPM:
    if: ${{ github.event.inputs.OnePlus13T_KPM == 'true' }}
    uses: ./.github/workflows/OnePlus13T_KPM.yml
    secrets: inherit
    
  OnePlusAce5Pro_KPM:
    if: ${{ github.event.inputs.OnePlusAce5Pro_KPM == 'true' }}
    uses: ./.github/workflows/OnePlusAce5Pro_KPM.yml
    secrets: inherit
    